definitions:
  config:
    /hst:hst/hst:hosts/kube/site:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhost
      /hippo:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:homepage: root
          hst:mountpoint: /hst:hst/hst:sites/myhippoproject
          hst:showcontextpath: false
